### ISSUE TITLE
Not highlighting matches

### ISSUE THREAD

**Issue by animike** [YoungFrog/highlight-region#1]
I try the code using M-x highlight-region-mode and no error messages, the mode is activated successfully, but doesn't work as expected, because marking region does not highlight matches, and there is a conflict with double click marking, it marks to the left only.

**Comment by YoungFrog** [comment]
Do you have any error message in the _Messages_ buffer ? I tried addressing a potential issue in 2d167b4 just now. Here's a test which works for me : run `emacs -Q -l highlight-region.el -f highlight-region-mode` then insert two semicolons, hit C-SPC (activate the mark) and C-a. It should highlight the semi colons on the previous two lines (inserted by emacs) with a yellow face, in addition to the region (which is also highlighted with another face).

**Comment by animike** [comment]
No error messages in the message buffer.

It worked now with 2d167b4, but I can't run the test yet, because I started using Emacs 2 weeks ago, and have not had a reason until now to install experimental packages, I only see elpa and melpa packages with M-x list-packages. How can I install and update this package correctly? Could you please show me a link or tell me a tool for achieving this?

**Comment by animike** [comment]
I switched back to copy the Emacs Stack Exchange code and extrangely this time I had a error (didn't have it priorly)

> Highlight-Region mode enabled
> Error in post-command-hook (highlight-region--highlight-region): (void-function string-empty-p)

Anyways with https://github.com/YoungFrog/highlight-region/commit/2d167b4315570e9e9959a1c8bf7d58da4dc04a88 works fine, I will be using it with selected.el as I code to test it.

**Comment by YoungFrog** [comment]
I did not package this file, so there's no update procedure other than grabbing the new file and saving it instead of the old one + evaluate the new code. Besides, thanks for confirming that the code works now.

**Comment by animike** [comment]
That's how it is done then. Glad to help, thanks to you too.
